trigger:
- main

variables:
  location: 'southcentralus'
  siteFilePath: '$(Build.SourcesDirectory)/scc-webapp/sitefiles'

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Deploy
        pool: msi-pool
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'scc-sc'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Deploy the Bicep template and capture the outputs

                $outputs = az deployment sub create --location '$(location)' --template-file main.bicep --query properties.outputs | ConvertFrom-Json

                # Extract the resource group name, storage account name, and storage container name from the outputs

                $RESOURCE_GROUP_NAME = $outputs.resourceGroupName.value
                $STORAGE_ACCOUNT_NAME = $outputs.storageAccountName.value
                $STORAGE_CONTAINER_NAME = $outputs.storageContainerName.value.Split('/')[0]

                # Set the extracted values as pipeline variables

                Write-Host "##vso[task.setvariable variable=RESOURCE_GROUP_NAME]$RESOURCE_GROUP_NAME"

                Write-Host "##vso[task.setvariable variable=STORAGE_ACCOUNT_NAME]$STORAGE_ACCOUNT_NAME"

                Write-Host "##vso[task.setvariable variable=STORAGE_CONTAINER_NAME]$STORAGE_CONTAINER_NAME"

          - powershell: |
              Write-Host "RESOURCE_GROUP_NAME: $(SetVariables.RESOURCE_GROUP_NAME)"
              Write-Host "STORAGE_ACCOUNT_NAME: $(SetVariables.STORAGE_ACCOUNT_NAME)"
              Write-Host "STORAGE_CONTAINER_NAME: $(SetVariables.STORAGE_CONTAINER_NAME)"
            displayName: 'Display pipeline variables'