trigger:
- main

variables:
  location: 'southcentralus'
  siteFilePath: '$(Build.SourcesDirectory)/scc-webapp/sitefiles'

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Deploy
        pool: msi-pool
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'scc-sc'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Deploy the Bicep template and capture the outputs

                $outputs = az deployment sub create --location '$(location)' --template-file main.bicep --query properties.outputs | ConvertFrom-Json

                # Extract the resource group name, storage account name, and storage container name from the outputs

                $RESOURCE_GROUP_NAME = $outputs.resourceGroupName.value
                $STORAGE_ACCOUNT_NAME = $outputs.storageAccountName.value
                $STORAGE_CONTAINER_NAME = $outputs.storageContainerName.value

                # Set the extracted values as pipeline variables

                Write-Host '##vso[task.setvariable variable=RESOURCE_GROUP_NAME]$RESOURCE_GROUP_NAME'
                Write-Host '##vso[task.setvariable variable=STORAGE_ACCOUNT_NAME]$STORAGE_ACCOUNT_NAME'
                Write-Host '##vso[task.setvariable variable=STORAGE_CONTAINER_NAME]$STORAGE_CONTAINER_NAME'
      
  - stage: UploadSiteFiles
    dependsOn: DeployInfrastructure
    jobs:
      - job: Upload
        pool: msi-pool
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'scc-sc'
              KeyVaultName: 'scc-vault'
              SecretsFilter: 'connectionString'
              RunAsPreJob: true

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'scc-sc'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $connectionString = $(az keyvault secret show --name 'connectionString' --vault-name 'scc-vault' --query 'value' -o tsv)
                $storageContainerName = "${env:STORAGE_CONTAINER_NAME}"
                $siteFilePath = "${env:siteFilePath}"
                az storage blob upload-batch --destination $storageContainerName --source $siteFilePath