trigger:
  - main

variables:
  location: "southcentralus"
  siteFilePath: "$(Build.SourcesDirectory)/scc-webapp/sitefiles"

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Deploy
        pool: msi-pool
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "scc-sc"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Deploy the Bicep template and capture the outputs

                $outputs = az deployment sub create --location '$(location)' --template-file main.bicep --query properties.outputs | ConvertFrom-Json


                # Extract the resource group name, storage account name, and storage container name from the outputs

                $RESOURCE_GROUP_NAME = $outputs.resourceGroupName.value

                $STORAGE_ACCOUNT_NAME = $outputs.storageAccountName.value

                $STORAGE_CONTAINER_PATH = $outputs.storageContainerName.value

                $STORAGE_CONTAINER_NAME = $STORAGE_CONTAINER_PATH.Split('/')[-1]


                # Print out the values to confirm they were captured correctly

                Write-Host "Resource Group Name: $RESOURCE_GROUP_NAME"

                Write-Host "Storage Account Name: $STORAGE_ACCOUNT_NAME"

                Write-Host "Storage Container Path: $STORAGE_CONTAINER_PATH"

                Write-Host "Storage Container Name: $STORAGE_CONTAINER_NAME"


                # Set the output variables for use in subsequent stages

                Write-Host "##vso[task.setvariable variable=resourceGroupName;isOutput=true]$RESOURCE_GROUP_NAME"

                Write-Host "##vso[task.setvariable variable=storageAccountName;isOutput=true]$STORAGE_ACCOUNT_NAME"

                Write-Host "##vso[task.setvariable variable=storageContainerName;isOutput=true]$STORAGE_CONTAINER_NAME"

  - stage: UploadSiteFiles
    dependsOn: DeployInfrastructure
    jobs:
      - job: Upload
        pool: msi-pool
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "scc-sc"
              KeyVaultName: "scc-vault"
              SecretsFilter: "connectionString" 

          - task: AzureCLI@2
            inputs:
              azureSubscription: "scc-sc"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Get the connection string for the storage account

                $connectionString = az storage account keys list --resource-group "$(RESOURCE_GROUP_NAME)" --account-name "$(STORAGE_ACCOUNT_NAME)" --query '[0].value' -o tsv

                # Upload the site files to the storage account

                az storage blob upload-batch --connection-string $connectionString --destination "$(STORAGE_CONTAINER_NAME)" --source "$(siteFilePath)" --pattern '*'