trigger:
  - main

pool: msi-pool

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "scc-sc"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                $output = az deployment sub create --location 'southcentralus' --template-file main.bicep --query "{ storageAccountName:properties.outputs.storageAccountName.value, storageContainerName:properties.outputs.storageContainerName.value}" --output json
                $deployment = $output | ConvertFrom-Json

                # convert storage details to pipeline variables
                echo "##vso[task.setvariable variable=storageAccountName]$($deployment.storageAccountName)"
                echo "##vso[task.setvariable variable=storageContainerName]$($deployment.storageContainerName)"
                
                # Display the storage account and container names in the console
                Write-Host "Storage Account Name: $($deployment.storageAccountName)"
                Write-Host "Storage Container Name: $($deployment.storageContainerName.Split('/')[-1])"
                Write-Host "Pipeline Workspace: $(Pipeline.Workspace)"
                Write-Host "System Default Working Directory: $(System.DefaultWorkingDirectory)"